# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'GitTest' do
  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
end
